# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('everyday', '0002_auto_20170302_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='BTS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ECP', models.CharField(max_length=10)),
                ('UCN', models.CharField(max_length=10)),
                ('adress', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='personel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
            ],
        ),
    ]
