# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-02-26 08:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('everyday', '0003_auto_20190225_1742'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wtype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('dept', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='everyday.Dept')),
            ],
        ),
        migrations.RemoveField(
            model_name='work',
            name='dept',
        ),
        migrations.AddField(
            model_name='work',
            name='wtype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='everyday.Wtype'),
        ),
    ]
