# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 16:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('everyday', '0004_auto_20170302_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='personel',
            name='Position',
            field=models.CharField(default='SOME STRING', max_length=50),
        ),
        migrations.AlterField(
            model_name='dte',
            name='executor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='everyday.personel', to_field='Name'),
        ),
        migrations.AlterField(
            model_name='personel',
            name='Name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
