# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-11-13 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('everyday', '0006_auto_20170302_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dte',
            name='executor',
        ),
        migrations.AddField(
            model_name='dte',
            name='executor',
            field=models.ManyToManyField(to='everyday.personel'),
        ),
        migrations.AlterField(
            model_name='dte',
            name='nn',
            field=models.IntegerField(),
        ),
    ]
