# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-11-14 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('everyday', '0007_auto_20181113_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='dte',
            name='dept',
            field=models.CharField(default='', max_length=20),
        ),
    ]
