# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-11-14 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('everyday', '0008_dte_dept'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dn', models.CharField(default='', max_length=8, unique=True)),
                ('driver', models.CharField(max_length=20)),
            ],
        ),
    ]
