# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-11-14 08:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('everyday', '0009_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='dte',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='everyday.Car'),
        ),
    ]
