# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-11-14 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('everyday', '0010_dte_car'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edrpou', models.IntegerField()),
                ('name', models.CharField(max_length=80)),
                ('address', models.CharField(max_length=80)),
            ],
        ),
        migrations.AddField(
            model_name='bts',
            name='dn',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bts',
            name='adress',
            field=models.CharField(max_length=80),
        ),
    ]
