# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-11-14 09:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('everyday', '0011_auto_20181114_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='bts',
            name='contra',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='everyday.Contra'),
            preserve_default=False,
        ),
    ]
