# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-11-14 13:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import everyday.models


class Migration(migrations.Migration):

    dependencies = [
        ('everyday', '0012_bts_contra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dte',
            name='ESN',
        ),
        migrations.AlterField(
            model_name='dte',
            name='adress',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='everyday.BTS'),
        ),
        migrations.AlterField(
            model_name='dte',
            name='created_date',
            field=models.DateTimeField(default=everyday.models.yesterday),
        ),
    ]
