# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-03-01 07:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('everyday', '0013_dte_work'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('workcode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='everyday.Wtype')),
            ],
        ),
        migrations.RemoveField(
            model_name='work',
            name='wtype',
        ),
        migrations.AddField(
            model_name='work',
            name='workcode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='everyday.WorkCode'),
        ),
    ]
