# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-11-14 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('everyday', '0013_auto_20181114_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='model',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='dte',
            name='executor',
            field=models.ManyToManyField(null=True, to='everyday.personel'),
        ),
    ]
