# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-11-19 12:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('everyday', '0014_auto_20181114_1638'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bts',
            options={'ordering': ['adress']},
        ),
        migrations.AlterField(
            model_name='bts',
            name='adress',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bts',
            name='contra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='everyday.Contra'),
        ),
        migrations.AlterField(
            model_name='contra',
            name='address',
            field=models.CharField(max_length=100),
        ),
    ]
