# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-11-19 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('everyday', '0015_auto_20181119_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dte',
            name='executor',
            field=models.ManyToManyField(to='everyday.personel'),
        ),
    ]
