# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-11-19 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('everyday', '0016_auto_20181119_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bts',
            name='adress',
            field=models.CharField(max_length=200),
        ),
    ]
