# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-11-19 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('everyday', '0019_auto_20181119_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dte',
            name='note',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
