# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-14 08:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('activ', models.IntegerField()),
                ('text', models.TextField()),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Teg', models.CharField(max_length=50, unique=True)),
                ('Position', models.CharField(default='SOME STRING', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='ads',
            name='tegs',
            field=models.ManyToManyField(to='ads.tags'),
        ),
    ]
